apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-postgres
  labels: 
    app: pokedex-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokedex-postgres
  template:
    metadata:
      labels:
        app: pokedex-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pokedex-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: pokedex-postgres-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  name: pokedex-postgres
  labels:
    app: pokedex-postgres
spec:
  selector:
    app: pokedex-postgres
  type: LoadBalancer
  ports:
   - port: 5432
     nodePort: 31544
